# Based on
# - https://github.com/marketplace/actions/setup-go-environment

name: go-test-darwin.yaml

on: [push]

env:
  SENZING_TOOLS_DATABASE_URL: "sqlite3://na:na@/tmp/sqlite/G2C.db"
  LD_LIBRARY_PATH: /opt/senzing/g2/lib:/opt/senzing/g2/lib/macos
  DYLD_LIBRARY_PATH: /opt/senzing/g2/lib:/opt/senzing/g2/lib/macos
  
jobs:
  build:
    runs-on: macos-latest
    env:
      GO111MODULE: on
      CGO_ENABLED: 1
      # PATH: $PATH:/Users/runner/work/g2-sdk-go-base/g2-sdk-go-base/bin
    strategy:
      matrix:
        go: ["1.20"]
    name: Go ${{ matrix.go }} - darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Download SenzingApi
        run: curl --output /tmp/senzingapi.dmg https://public-read-access.s3.amazonaws.com/staging/senzingapi.dmg
      - name: Attach .dmg
        run: hdiutil attach /tmp/senzingapi.dmg
      - name: Copy SenzingApi files
        run: sudo mkdir -p /opt/senzing/    && sudo cp -R /Volumes/SenzingAPI/senzing/g2 /opt/senzing
      - name: Copy /etc files
        run: sudo mkdir -p /etc/opt/senzing && sudo cp testdata/senzing-license/g2.lic /etc/opt/senzing
      - name: Copy test database fies
        run: mkdir /tmp/sqlite && cp testdata/sqlite/G2C.db /tmp/sqlite/G2C.db
      # - name: Run go test
      #   run: go test -exec /Users/runner/work/g2-sdk-go-base/g2-sdk-go-base/bin/macos_exec_dyld.sh -v -p 1 ./...
      - name: Run go test - main
        run: go test -exec /Users/runner/work/g2-sdk-go-base/g2-sdk-go-base/bin/macos_exec_dyld.sh -v -p 1 ./.
      - name: Run go test - main
        run: go test -exec /Users/runner/work/g2-sdk-go-base/g2-sdk-go-base/bin/macos_exec_dyld.sh -v -p 1 ./g2config
      - name: Run go test - main
        run: go test -exec /Users/runner/work/g2-sdk-go-base/g2-sdk-go-base/bin/macos_exec_dyld.sh -v -p 1 ./g2configmgr
