# Based on
# - https://github.com/marketplace/actions/setup-go-environment

name: go-test-darwin.yaml

on: [push]

env:
  DYLD_LIBRARY_PATH: /opt/senzing/g2/lib:/opt/senzing/g2/lib/macos
  LD_LIBRARY_PATH: /opt/senzing/g2/lib:/opt/senzing/g2/lib/macos
  SENZING_TOOLS_DATABASE_URL: "sqlite3://na:na@/tmp/sqlite/G2C.db"
  SENZING_TOOLS_ENABLE_ALL: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.20"]
    name: Go ${{ matrix.go }} - darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - name: Download SenzingApi
        run: curl --output /tmp/senzingapi.dmg https://public-read-access.s3.amazonaws.com/staging/senzingapi.dmg
      - name: Attach .dmg
        run: hdiutil attach /tmp/senzingapi.dmg
      - name: Copy SenzingApi files
        run: sudo mkdir -p /opt/senzing/    && sudo cp -R /Volumes/SenzingAPI/senzing/g2 /opt/senzing
      - name: Copy /etc files
        run: sudo mkdir -p /etc/opt/senzing && sudo cp testdata/senzing-license/g2.lic /etc/opt/senzing
      - name: Copy test database fies
        run: mkdir /tmp/sqlite && cp testdata/sqlite/G2C.db /tmp/sqlite/G2C.db
      - name: gRPC service
        run: docker run --detach --env SENZING_TOOLS_ENABLE_ALL --publish 8261:8261 senzing/serve-grpc:latest
      - name: Run go test
        run: go test -exec /Users/runner/work/go-sdk-abstract-factory/go-sdk-abstract-factory/bin/macos_exec_dyld.sh -v -p 1 ./...
