name: go test linux

on: [push]

env:
  LD_LIBRARY_PATH: /opt/senzing/g2/lib
  SENZING_ACCEPT_EULA: I_ACCEPT_THE_SENZING_EULA
  SENZING_TOOLS_DATABASE_URL: "sqlite3://na:na@/tmp/sqlite/G2C.db"

permissions:
  contents: read

jobs:
  go-test-linux:
    env:
      GO111MODULE: on
      LD_LIBRARY_PATH: /opt/senzing/g2/lib/
      CGO_ENABLED: 1
    name: "go test with Senzing: ${{ matrix.senzingapi-version }}; OS: ${{ matrix.os }}; Go: ${{ matrix.go }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.21"]
        os: [ubuntu-latest]
        senzingapi-version: [latest]

    services:
      servegrpc:
        env:
          SENZING_TOOLS_ENABLE_ALL: true
        image: senzing/serve-grpc
        ports:
          - 8261:8261

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: install Senzing API
        uses: senzing-factory/github-action-install-senzing-api@v2
        with:
          senzingapi-version: ${{ matrix.senzingapi-version }}

      - name: copy /etc files
        run: sudo cp testdata/senzing-license/g2.lic /etc/opt/senzing/g2.lic

      - name: copy test database files
        run: mkdir /tmp/sqlite && cp testdata/sqlite/G2C.db /tmp/sqlite/G2C.db

      - name: run go test
        run: go test -v -p 1 ./...
